version: "3.9"
services:

 redis-go-server:
   build:
     context: ./
   environment:
     - REDIS_DB_URL=redis-db:6379
     - REDIS_DB_PASSWORD=
     - REDIS_DB=0
   ports:
     - "8080:8080"
   container_name: redis-go-server
   depends_on:
     - redis-cache
     - postgres

 redis-cache:
   image: redis:alpine
   ports:
     - 6379:6379
   container_name: redis-cache
   
 postgres:
   container_name: my_bd
   image: postgres:13.3
   command:
     - "postgres"
     - "-c"
     - "max_connections=50"
     - "-c"
     - "shared_buffers=1GB"
     - "-c"
     - "effective_cache_size=4GB"
     - "-c"
     - "work_mem=16MB"
     - "-c"
     - "maintenance_work_mem=512MB"
     - "-c"
     - "random_page_cost=1.1"
     - "-c"
     - "temp_file_limit=10GB"
     - "-c"
     - "log_min_duration_statement=200ms"
     - "-c"
     - "idle_in_transaction_session_timeout=10s"
     - "-c"
     - "lock_timeout=1s"
     - "-c"
     - "statement_timeout=60s"
     - "-c"
     - "shared_preload_libraries=pg_stat_statements"
     - "-c"
     - "pg_stat_statements.max=10000"
     - "-c"
     - "pg_stat_statements.track=all"
   environment:
     POSTGRES_DB: "lab01db"
     POSTGRES_USER: "andrew"
     POSTGRES_PASSWORD: "1"
     PGDATA: "/var/lib/postgresql/data/pgdata"
   ports:
     - "5432:5432"
   restart: unless-stopped
   deploy:
     resources:
       limits:
         cpus: '1'
         memory: 4G

 pgadmin:
   container_name: pgadmin_container
   image: dpage/pgadmin4:7.2
   environment:
     PGADMIN_DEFAULT_EMAIL: "ggwpez@amil.ru"
     PGADMIN_DEFAULT_PASSWORD: "1"
     PGADMIN_CONFIG_SERVER_MODE: "False"
   volumes:
     - pgadmin-data:/var/lib/pgadmin
   ports:
     - "5050:80"
   restart: unless-stopped
   deploy:
     resources:
       limits:
         cpus: '0.5'
         memory: 1G



volumes:
 pgadmin-data: